#!/bin/bash
## DOC: script que permet de voir combien de versions on a sur un fichier

usage() {
        echo "usage: $(basename "$0") <node_name> <file_name>" 
}

if [ $# -ne 2 ] ; then
        usage >&2
        exit -1
else
echo "##########################################"
echo "##"
echo "#    node_name: $1"
echo "#    file_name: $2"
echo
qtsm "select NODE_NAME,FILESPACE_NAME,HL_NAME,LL_NAME,BACKUP_DATE,CLASS_NAME,STATE from backups where NODE_NAME LIKE UPPER('%$1%') and upper(LL_NAME) LIKE UPPER('%$2%')"
fi
