---
chdir: /opt/eztsm
environment: production
address: 0.0.0.0
port: 3000
timeout: 30
log: /opt/eztsm/log/thin.log
pid: /opt/eztsm/tmp/pids/thin.pid
socket: /opt/eztsm/tmp/sockets/thin.sock
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
servers: 4
daemonize: true

